/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/system-requirements', 'getting-started/terms', 'getting-started/benefits', 'getting-started/about-product'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Personal Account',
      items: ['personal-account/registration', 'personal-account/review', 'personal-account/plans-description', 'personal-account/license-upgrade', 'personal-account/billing', 'personal-account/configurations', 'personal-account/referral-program', 'personal-account/help', 'personal-account/download', 'personal-account/services'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Cloud Dashboard',
      items: ['cloud-dashboard/my-account', 'cloud-dashboard/users', 'cloud-dashboard/profiles', 'cloud-dashboard/groups', 'cloud-dashboard/roles', 'cloud-dashboard/configs', 'cloud-dashboard/sessions', 'cloud-dashboard/services', 'cloud-dashboard/help-cloud', 'cloud-dashboard/download-cloud', ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Program',
      items: [
        'program/authentication',
        {
          type: 'category',
          label: 'Start Page',
          items: [
            'program/start-window/overview-main-window', 'program/start-window/creating-new-profile', 'program/start-window/mass-creation', 'program/start-window/profile-manager', 'program/start-window/proxy-manager', 'program/start-window/tag-manager', 'program/start-window/configs-manager', 'program/start-window/bot', 'program/start-window/help', 'program/start-window/settings',
          ],
        },
        {
          type: 'category',
          label: 'Browser',
          items: [
            'program/browser/main-window', 'program/browser/menu-browser', 'program/browser/profile-settings',
          ],
        }
      ]
    },
    'faq'
  ],

};

module.exports = sidebars;