/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/system-requirements', 'getting-started/purchase', 'getting-started/installing', 'getting-started/glossary', 'getting-started/faq'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Licenses',
      items: ['licenses/tariff', 'licenses/user-management'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Application',
      items: ['application/create-new-profile', 'application/mass-profiles', 'application/profiles-manager', 'application/proxy-manager', 'application/config-manager', 'application/tag-manager', 'application/bot-cookies', 'application/program-settings'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Proxy',
      items: ['proxy/ssh'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Browser',
      items: ['browser/autosave-password', 'browser/bookmarks', 'browser/history'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['integrations/partners'],
      collapsed: true,
    },
  ],
   
};

module.exports = sidebars;
